import type { GuidelineChunk } from "./types.js";

const now = "2026-01-01T00:00:00.000Z";

export const DEFAULT_GUIDELINES: GuidelineChunk[] = [
  {
    id: "guideline-general-star",
    sourceType: "rule",
    language: "en",
    title: "STAR / action-result resume bullet writing",
    content: "Resume bullets should follow an action-context-result structure. Emphasize concrete actions, methods, scope, and verifiable outcomes. Avoid unsupported metrics and ownership claims.",
    tags: ["STAR", "resume", "bullet", "action", "result", "faithfulness"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-general-truth-boundary",
    sourceType: "rule",
    language: "en",
    title: "Factual boundary and no-fabrication rule",
    content: "Do not invent companies, roles, metrics, leadership, product launches, revenue, users, or skills. If evidence is weak, use conservative wording or ask for confirmation.",
    tags: ["truth", "evidence", "risk", "no fabrication", "claims"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-product-role",
    sourceType: "role_template",
    roleFamily: "product",
    industry: "technology",
    applicationType: "internship",
    language: "en",
    title: "Product / product analyst resume strategy",
    content: "For product-related roles, prioritize user research, problem framing, market or competitor analysis, data-informed decisions, stakeholder communication, and product recommendations. Prefer wording that connects evidence to product impact without overstating launch ownership.",
    tags: ["product", "product analyst", "user research", "market analysis", "data", "stakeholder"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-software-role",
    sourceType: "role_template",
    roleFamily: "software",
    industry: "technology",
    applicationType: "internship",
    language: "en",
    title: "Software engineering resume strategy",
    content: "For software engineering roles, emphasize technical ownership only when supported, implementation details, system design tradeoffs, testing, performance, reliability, maintainability, and collaboration. Keep technology keywords explicit and evidence-backed.",
    tags: ["software", "engineering", "implementation", "testing", "performance", "system design"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-research-role",
    sourceType: "role_template",
    roleFamily: "research",
    applicationType: "research",
    language: "en",
    title: "Research application resume strategy",
    content: "For research applications, prioritize research questions, methodology, experimental rigor, publications, benchmarks, ablations, reproducibility, and collaboration. Avoid business-impact language unless the evidence directly supports it.",
    tags: ["research", "publication", "methodology", "experiment", "benchmark", "reproducibility"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-education-awards",
    sourceType: "rule",
    applicationType: "school",
    language: "en",
    title: "Education and awards presentation",
    content: "Education and awards should be concise and factual. Group scholarships and honors clearly. Do not over-explain awards unless they support the target role or application focus.",
    tags: ["education", "award", "scholarship", "honor", "school"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "guideline-zh-general",
    sourceType: "rule",
    language: "zh",
    title: "中文简历通用写作规则",
    content: "中文简历应保持事实清楚、动作明确、结果可验证。可以优化表达角度，但不能新增没有证据的项目、岗位、指标、奖项或技能。",
    tags: ["中文", "简历", "事实", "项目", "经历", "可信"],
    metadata: { builtIn: true },
    createdAt: now,
    updatedAt: now,
  },
];
