import type { ApplicationType, GuidelineChunk, GuidelineLanguage, GuidelineRoleFamily, GuidelineRuleKind, GuidelineSourceType } from "./types.js";

const now = "2026-01-01T00:00:00.000Z";

type Seed = {
  id: string;
  title: string;
  content: string;
  tags: string[];
  sourceType?: GuidelineSourceType;
  roleFamily?: GuidelineRoleFamily;
  applicationType?: ApplicationType;
  language?: GuidelineLanguage;
  ruleKind?: GuidelineRuleKind;
  mandatory?: boolean;
  section?: string;
  industry?: string;
};

function guideline(seed: Seed): GuidelineChunk {
  return {
    id: seed.id,
    sourceType: seed.sourceType ?? "rule",
    roleFamily: seed.roleFamily,
    industry: seed.industry,
    applicationType: seed.applicationType,
    language: seed.language ?? "en",
    title: seed.title,
    content: seed.content,
    tags: seed.tags,
    metadata: {
      builtIn: true,
      mandatory: seed.mandatory ?? false,
      ruleKind: seed.ruleKind ?? "writing_rule",
      priority: seed.mandatory ? 100 : 50,
      section: seed.section,
      provenance: "curated_builtin",
    },
    createdAt: now,
    updatedAt: now,
  };
}

export const DEFAULT_GUIDELINES: GuidelineChunk[] = [
  guideline({
    id: "guideline-en-truth-boundary",
    title: "Evidence-bound factual writing",
    content: "Use only user-provided or Evidence-Pack-supported facts. Do not invent companies, roles, projects, skills, metrics, leadership, launches, publications, awards, users, revenue, or outcomes. Missing evidence must be omitted or explicitly confirmed by the user.",
    tags: ["truth", "evidence", "no fabrication", "factual boundary", "claims"],
    mandatory: true,
    ruleKind: "hard_constraint",
  }),
  guideline({
    id: "guideline-zh-truth-boundary",
    title: "证据边界与禁止虚构",
    content: "只使用用户提供或 Evidence Pack 明确支持的事实。不得新增公司、岗位、项目、技能、指标、领导职责、上线成果、论文、奖项、用户规模或业务结果。证据缺失时应省略或请求用户确认。",
    tags: ["事实", "证据", "禁止虚构", "可信", "边界"],
    language: "zh",
    mandatory: true,
    ruleKind: "hard_constraint",
  }),
  guideline({
    id: "guideline-en-ownership-boundary",
    title: "Preserve actual ownership level",
    content: "Keep the candidate's ownership level faithful. Use led, owned, drove, managed, or launched only when direct evidence supports leadership or end-to-end responsibility; otherwise use contributed, implemented, analyzed, supported, or collaborated.",
    tags: ["ownership", "leadership", "verbs", "risk", "evidence"],
    mandatory: true,
    ruleKind: "hard_constraint",
  }),
  guideline({
    id: "guideline-zh-ownership-boundary",
    title: "保持真实职责边界",
    content: "严格保持用户真实职责层级。只有证据明确支持主导、管理或端到端负责时，才能使用“主导”“负责”“推动上线”等强表述；否则使用“参与”“实现”“分析”“协助”或“合作完成”。",
    tags: ["职责", "主导", "包装力度", "风险", "事实"],
    language: "zh",
    mandatory: true,
    ruleKind: "hard_constraint",
  }),
  guideline({
    id: "guideline-en-action-result",
    title: "Action-method-result bullet structure",
    content: "Write bullets with action, technical or analytical method, scope, and verified result. Prefer one clear contribution per bullet and avoid vague responsibility-only descriptions.",
    tags: ["STAR", "action", "method", "result", "bullet"],
    ruleKind: "writing_rule",
    section: "experience",
  }),
  guideline({
    id: "guideline-zh-action-result",
    title: "行动方法结果式经历表述",
    content: "经历要点优先采用“行动 + 方法 + 范围 + 可验证结果”的结构，每条突出一个清晰贡献，避免仅罗列职责或使用空泛形容词。",
    tags: ["行动", "方法", "结果", "经历", "要点"],
    language: "zh",
    ruleKind: "writing_rule",
    section: "experience",
  }),
  guideline({
    id: "guideline-en-ats-keywords",
    title: "Evidence-backed ATS keyword use",
    content: "Use exact JD terminology for supported skills and responsibilities, but integrate keywords naturally into evidence-backed bullets. Do not copy large JD passages or add unsupported keywords solely for ATS coverage.",
    tags: ["ATS", "keyword", "JD", "skills", "natural language"],
    ruleKind: "writing_rule",
  }),
  guideline({
    id: "guideline-zh-ats-keywords",
    title: "基于证据的关键词匹配",
    content: "对已有证据支持的技能和职责可使用 JD 中的准确术语，但应自然融入经历表述。不得为了 ATS 覆盖而照抄大段 JD 或补充用户没有的技能。",
    tags: ["ATS", "关键词", "岗位", "技能", "证据"],
    language: "zh",
    ruleKind: "writing_rule",
  }),
  guideline({
    id: "guideline-en-metrics",
    title: "Verified metrics and scope",
    content: "Retain only metrics, rankings, dates, scale, and performance gains explicitly present in user evidence. Never estimate a number. When impact is qualitative, describe the verified technical or operational outcome without fabricating a metric.",
    tags: ["metrics", "numbers", "scope", "impact", "verification"],
    mandatory: true,
    ruleKind: "hard_constraint",
  }),
  guideline({
    id: "guideline-en-prioritization",
    title: "One-page relevance prioritization",
    content: "Prioritize the strongest evidence for critical JD requirements. Remove redundant or low-relevance material before compressing important evidence. Distinctive evidence should outrank generic credentials.",
    tags: ["one page", "prioritization", "relevance", "selection", "compression"],
    ruleKind: "selection_rule",
  }),
  guideline({
    id: "guideline-ai-ml-role",
    sourceType: "role_template",
    roleFamily: "ai_ml",
    industry: "technology",
    title: "AI and machine learning engineering strategy",
    content: "Prioritize model or agent design, data and evaluation pipelines, experimental methodology, optimization, deployment constraints, and reproducible results. Name frameworks only when used. Separate research novelty from engineering contribution and do not imply production deployment without evidence.",
    tags: ["AI", "machine learning", "LLM", "agent", "evaluation", "PyTorch", "deployment"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-ai-ml-pattern",
    sourceType: "example_resume",
    roleFamily: "ai_ml",
    title: "Safe AI/ML project pattern",
    content: "Designed and evaluated [verified model or agent component] using [verified method or framework], achieving [verified metric or qualitative outcome] on [verified dataset or application context].",
    tags: ["AI", "ML", "pattern", "experiment", "metric"],
    ruleKind: "example_pattern",
  }),
  guideline({
    id: "guideline-software-role",
    sourceType: "role_template",
    roleFamily: "software",
    industry: "technology",
    title: "Software engineering strategy",
    content: "Emphasize implementation, architecture decisions, interfaces, testing, reliability, performance, maintainability, and collaboration. Make the candidate's concrete code or system contribution explicit and avoid claiming system ownership beyond evidence.",
    tags: ["software", "engineering", "system design", "testing", "performance", "reliability"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-software-pattern",
    sourceType: "example_resume",
    roleFamily: "software",
    title: "Safe software engineering pattern",
    content: "Implemented [verified component] with [verified technologies], improving [verified technical property] by [verified metric] or enabling [verified capability].",
    tags: ["software", "implementation", "pattern", "technology"],
    ruleKind: "example_pattern",
  }),
  guideline({
    id: "guideline-data-role",
    sourceType: "role_template",
    roleFamily: "data",
    title: "Data and analytics strategy",
    content: "Prioritize data preparation, analytical methods, experiment or metric design, insight quality, dashboards or pipelines, and decisions enabled by the analysis. Distinguish correlation, prediction, and causal claims carefully.",
    tags: ["data", "analytics", "SQL", "dashboard", "experiment", "insight"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-product-role",
    sourceType: "role_template",
    roleFamily: "product",
    industry: "technology",
    title: "Product and product analyst strategy",
    content: "Prioritize user research, problem framing, market or competitor analysis, data-informed decisions, stakeholder communication, and product recommendations. Do not convert recommendations into launched features or business results without evidence.",
    tags: ["product", "user research", "market analysis", "stakeholder", "recommendation"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-research-role",
    sourceType: "role_template",
    roleFamily: "research",
    applicationType: "research",
    title: "Research application strategy",
    content: "Prioritize research questions, methodology, experimental rigor, baselines, ablations, reproducibility, publications, patents, and the candidate's exact contribution. Use publication status accurately and avoid overstating authorship or novelty.",
    tags: ["research", "publication", "methodology", "experiment", "benchmark", "ablation"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-research-pattern",
    sourceType: "example_resume",
    roleFamily: "research",
    applicationType: "research",
    title: "Safe research contribution pattern",
    content: "Investigated [verified research question] by developing [verified method], evaluating it against [verified baselines] on [verified datasets], and contributing [verified authorship or research role].",
    tags: ["research", "method", "baseline", "dataset", "pattern"],
    ruleKind: "example_pattern",
  }),
  guideline({
    id: "guideline-consulting-role",
    sourceType: "role_template",
    roleFamily: "consulting",
    title: "Consulting strategy",
    content: "Highlight structured problem solving, research, quantitative analysis, stakeholder communication, synthesis, and actionable recommendations. Do not describe a recommendation as implemented impact unless the user has evidence of implementation.",
    tags: ["consulting", "problem solving", "analysis", "stakeholder", "recommendation"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-finance-role",
    sourceType: "role_template",
    roleFamily: "finance",
    title: "Finance and quantitative strategy",
    content: "Prioritize financial or quantitative analysis, modeling assumptions, risk, market or company research, automation, and verified investment or operational outputs. Avoid implying trading performance, returns, or client responsibility without direct evidence.",
    tags: ["finance", "quant", "modeling", "risk", "market research"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-school-strategy",
    sourceType: "school_template",
    applicationType: "school",
    title: "Graduate and school application CV strategy",
    content: "Prioritize academic preparation, research potential, relevant projects, publications, honors, leadership, and service according to program fit. Keep the CV factual and avoid turning aspirations into completed achievements.",
    tags: ["school", "graduate", "academic", "research potential", "program fit"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-education-awards",
    applicationType: "school",
    title: "Education and awards presentation",
    content: "Keep degrees, dates, GPA, scholarships, rankings, and honors exact. Group related awards compactly and explain selectivity only when the source provides it.",
    tags: ["education", "award", "scholarship", "honor", "GPA"],
    ruleKind: "writing_rule",
    section: "education",
  }),
  guideline({
    id: "guideline-internship-strategy",
    sourceType: "role_template",
    applicationType: "internship",
    title: "Internship and early-career strategy",
    content: "For internships, foreground relevant projects, coursework, research, competitions, and learning velocity when formal work experience is limited. Do not inflate class projects into commercial deployments.",
    tags: ["internship", "student", "project", "coursework", "early career"],
    ruleKind: "selection_rule",
  }),
  guideline({
    id: "guideline-zh-ai-ml-role",
    sourceType: "role_template",
    roleFamily: "ai_ml",
    industry: "technology",
    language: "zh",
    title: "人工智能与算法岗位简历策略",
    content: "优先呈现模型或智能体设计、数据与评测流程、实验方法、优化、部署约束和可复现结果。框架名称必须来自真实使用经历，并区分研究创新、工程实现和业务落地，不能把实验原型写成生产部署。",
    tags: ["人工智能", "算法", "大模型", "智能体", "评测", "实验"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-zh-software-role",
    sourceType: "role_template",
    roleFamily: "software",
    language: "zh",
    title: "软件工程岗位简历策略",
    content: "突出具体实现、架构选择、接口设计、测试、性能、可靠性和协作贡献。明确用户真正编写或负责的模块，避免将参与开发包装为系统整体负责人。",
    tags: ["软件工程", "开发", "架构", "测试", "性能", "可靠性"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-zh-research-role",
    sourceType: "role_template",
    roleFamily: "research",
    applicationType: "research",
    language: "zh",
    title: "科研申请简历策略",
    content: "重点说明研究问题、方法、实验严谨性、基线与消融、可复现性、论文专利以及个人准确贡献。论文状态、作者顺序和创新点必须与证据一致。",
    tags: ["科研", "论文", "方法", "实验", "基线", "消融"],
    ruleKind: "section_strategy",
  }),
  guideline({
    id: "guideline-zh-school-strategy",
    sourceType: "school_template",
    applicationType: "school",
    language: "zh",
    title: "升学申请 CV 策略",
    content: "围绕项目匹配度呈现学术基础、科研潜力、相关项目、论文、荣誉、领导力与服务经历。保持事实准确，不把未来研究兴趣写成已经完成的成果。",
    tags: ["升学", "申请", "学术", "科研潜力", "项目匹配"],
    ruleKind: "section_strategy",
  }),
];
