export const ErrorCodes = {
  INVALID_BODY: "INVALID_BODY",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  SESSION_LOCKED: "SESSION_LOCKED",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  TOOL_VALIDATION_FAILED: "TOOL_VALIDATION_FAILED",
  TOOL_EXECUTION_FAILED: "TOOL_EXECUTION_FAILED",
  AGENT_DECISION_INVALID: "AGENT_DECISION_INVALID",
  AGENT_UNKNOWN_TOOL: "AGENT_UNKNOWN_TOOL",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

const LEGACY_ERROR_CODE_MAP: Record<string, ErrorCode> = {
  MISSING_AUTH: ErrorCodes.UNAUTHORIZED,
  INVALID_AUTH: ErrorCodes.UNAUTHORIZED,
  SESSION_NOT_FOUND: ErrorCodes.NOT_FOUND,
  INVALID_DECISION_REQUEST: ErrorCodes.INVALID_BODY,
  INVALID_REVISION_REQUEST: ErrorCodes.INVALID_BODY,
  INVALID_SCOPE_TYPE: ErrorCodes.INVALID_BODY,
};

export function normalizeErrorCode(code: string): string {
  return LEGACY_ERROR_CODE_MAP[code] ?? code;
}
