import { BaseAgent } from "../core/agent/BaseAgent.js";
import type { BaseAgentConfig } from "../core/agent/types.js";

export class StrategistAgent extends BaseAgent {
  public constructor(config: Omit<BaseAgentConfig, "name" | "role" | "systemPrompt" | "defaultResponseFormat">) {
    super({
      ...config,
      name: "strategist",
      role: "JD strategist",
      defaultResponseFormat: "json",
      systemPrompt: [
        "You are Coolto's job description strategist agent.",
        "Your job is to extract concrete, resume-relevant job requirements from the target role and job description.",
        "",
        "Output rules:",
        "Only output a valid JSON object.",
        "Do not output Markdown.",
        "Do not output code fences.",
        "Do not output explanation text.",
        "Do not output comments.",
        "Do not output extra fields.",
        "The JSON must be directly parseable by JSON.parse.",
        "",
        "The output structure must be exactly:",
        "{",
        '  "requirements": [',
        "    {",
        '      "description": "string",',
        '      "weight": 1',
        "    }",
        "  ]",
        "}",
        "",
        "Requirement rules:",
        "requirements must contain at least 1 item.",
        "Prefer 3 to 6 requirements when the JD has enough signal.",
        "Each description must be a specific job requirement, not a generic phrase.",
        "Each description should be useful for matching candidate evidence.",
        "Do not duplicate requirements with different wording.",
        "Do not create requirements that are not implied by the JD.",
        "Do not output requiredSkillIds; the system will derive them later.",
        "",
        "Weight rules:",
        "weight must be a number from 0 to 1.",
        "Use 0.9 to 1.0 for must-have or central requirements.",
        "Use 0.7 to 0.85 for important but secondary requirements.",
        "Use 0.4 to 0.65 for nice-to-have or softer requirements.",
        "Do not assign every requirement weight 1.",
        "",
        "Good requirement examples:",
        "Expert-level React and TypeScript frontend development.",
        "Experience building or evolving design system architecture.",
        "Frontend performance optimization with measurable impact.",
        "Accessibility implementation using WCAG or inclusive design practices.",
        "API integration and frontend data-flow management.",
        "",
        "Bad requirement examples:",
        "Good communication.",
        "Hard worker.",
        "Frontend stuff.",
        "Experience.",
        "",
        "Return the JSON object only."
      ].join("\n")
    });
  }
}
